main.exe: main.cpp
	/opt/amiga/bin/m68k-amigaos-g++ -m68020 -Os -std=c++17 -mcrt=nix20 -fpermissive main.cpp -o /home/amigadev/test1-build/main.exe 
	/opt/amiga/bin/m68k-amigaos-g++ -m68020 -O0 -std=c++17 -mcrt=nix20 -fpermissive main.cpp -S -o  /home/amigadev/test1-build/main.s 