version: '3.9'
services:
  ci-master:
    image: obtcicd/master_focal
    user: cimaster
    command: "./start-master.sh"
    #command: "./spin.sh"
    ports:
      - '0.0.0.0:16666:16666'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
  ci-worker-ub20:
    image: obtcicd/worker_focal 
    user: workerub20
    command: "./start-worker.sh"
    # use spin for manual debugging
    #command: "./spin.sh"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ../ci_secrets/buildkey.rsa:/home/workerub22/.ssh/id_rsa:ro
      - ../ci_secrets/buildkey.rsa.pub:/home/workerub22/.ssh/id_rsa.pub:ro
  ci-worker-ub22:
    image: obtcicd/worker_jammy
    user: workerub22
    command: "./start-worker.sh"
    # use spin for manual debugging
    #command: "./spin.sh"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ../ci_secrets/buildkey.rsa:/home/workerub22/.ssh/id_rsa:ro
      - ../ci_secrets/buildkey.rsa.pub:/home/workerub22/.ssh/id_rsa.pub:ro
    restart: always

